language: python
python:
  "3.4.5"
install: "pip install -r requirements.txt"
script: "python3 manage.py compilemessages && python3 manage.py test"
notifications:
  slack: osisteam:2M3DtIOGE4clU1DF8r6k8NQD
services:
  - postgresql
  - rabbitmq
addons:
    postgresql: "9.4"
after_sucess:
    - CODECLIMATE_REPO_TOKEN=37a30b73c9ca86e79442503327038e6b7fe540d4cdeec8ecde1bfe9a43e19d9a codeclimate-test-reporter
