# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 12:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_learningunitcomponent_coefficient_repetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='learning_container',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainer'),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='status',
            field=models.CharField(blank=True, choices=[('VALID', 'VALID'), ('INVALID', 'INVALID')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_draft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_reencoded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('ANNUAL', 'ANNUAL'), ('BIENNIAL_EVEN', 'BIENNIAL_EVEN'), ('BIENNIAL_ODD', 'BIENNIAL_ODD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='type',
            field=models.CharField(blank=True, choices=[('COURSE', 'COURSE'), ('MASTER_THESIS', 'MASTER_THESIS'), ('INTERNSHIP', 'INTERNSHIP')], max_length=20, null=True),
        ),
    ]
